# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f010de21a53ffac4478b7d7dff818f192ee9b143efcea611c72e99f6bf2033582b88597a583bfe858a28d6b6385f104f020510dfe739b3d6476230ff770094b6

test:
  secret_key_base: 0035b496e4076e68464c909debb0e836cf535a42638c335d069ec8f5d67e92c5cdd25e57bf739df4df2cb23a47756f8521194da956661a215f775e3e3b01267b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
